CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE device_status AS ENUM ('ACTIVE','INACTIVE','SUSPENDED','OFFLINE');
CREATE TYPE payment_status AS ENUM ('PENDING','SUCCESS','FAILED');
CREATE TYPE announcement_status AS ENUM ('PENDING','PUBLISHED','DELIVERED','FAILED');
CREATE TABLE merchants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),merchant_code varchar(40) UNIQUE NOT NULL,merchant_name varchar(120) NOT NULL,status varchar(20) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE devices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),device_code varchar(50) UNIQUE NOT NULL,merchant_id uuid NOT NULL REFERENCES merchants(id),serial_number varchar(80) UNIQUE NOT NULL,language varchar(5) NOT NULL CHECK(language IN ('en','hi','or','bn','ta','te')),status device_status NOT NULL,firmware_version varchar(30) NOT NULL,last_seen_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),transaction_reference varchar(80) UNIQUE NOT NULL,merchant_id uuid NOT NULL REFERENCES merchants(id),device_id uuid NOT NULL REFERENCES devices(id),amount numeric(14,2) NOT NULL CHECK(amount>0),currency char(3) NOT NULL,payment_status payment_status NOT NULL,announcement_status announcement_status NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE device_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),device_id uuid NOT NULL REFERENCES devices(id),event_type varchar(50) NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_devices_merchant_status ON devices(merchant_id,status);CREATE INDEX idx_transactions_merchant_created ON transactions(merchant_id,created_at DESC);CREATE INDEX idx_transactions_device_created ON transactions(device_id,created_at DESC);CREATE INDEX idx_device_events_device_created ON device_events(device_id,created_at DESC);
